// Curated content for the offline provider. Kept separate from the
// selection logic in providers/offline.ts so neither file grows unwieldy.
// Every entry should read as something a rapper who's actually thought about
// craft would hand another rapper - specific, concrete, nothing generic.

export const CONCEPTS: readonly string[] = [
  "Bragging about something small like it's a Grammy",
  "The moment you realize the block raised you more than your family did",
  "Making peace with the version of you that almost didn't make it",
  "Turning a text you never sent into sixteen bars",
  "The two-faced homie you still ride for anyway",
  "What it costs to be the first one in your family to leave",
  "A verse that only talks in dollar amounts and what they bought you",
  "The night you stopped believing your own hype",
  "Writing a eulogy for the person you were before the deal",
  "The flex that's really just fear wearing a chain",
  "A love letter to the city that never loved you back",
  "Counting exits, not blessings",
  "The last voicemail you never played back",
  "Getting rich enough to be lonely in a new way",
  "The year everyone stopped calling",
  "What you'd say to the version of you that's still inside",
  "The difference between surviving a block and belonging to it",
  "Turning a court date into a come-up story",
  "The homie who made it out and never looked back, from his side",
  "A verse where the jewelry does the talking so you don't have to",
  "What silence sounds like after the applause stops",
  "The math on what your mother sacrificed, itemized",
  "Talking to the version of you that's still locked up",
  "The first purchase that made it all feel real",
] as const;

export const SCENARIOS: readonly string[] = [
  "3 a.m., corner store lot, engine running, somebody's little brother asking for a ride nobody wants to give",
  "Back of a Crown Vic on the way to a court date, watching your city go by through bulletproof glass",
  "Standing in a walk-in closet bigger than your first apartment, still checking the price tags out of habit",
  "A funeral repast, paper plates, somebody's aunt playing the deceased's favorite song too loud",
  "First class for the first time, staring at the little bottle of liquor like it's a trophy",
  "The barbershop on a Saturday, everybody's got an opinion and nobody's paying for the cut",
  "A studio session at 4 a.m. where the engineer's asleep and you're still writing",
  "Your childhood bedroom, now a storage room, boxes stacked where the posters used to be",
  "A block party the week after a shooting, the DJ playing like nothing happened because that's the only way through it",
  "Sitting in a rental car outside your old building, engine off, not ready to go in yet",
  "The green room before a show, phone blowing up with numbers you don't recognize anymore",
  "A Sunday dinner where half the seats are empty and nobody says why",
  "Pawn shop counter, handing over the one thing you swore you'd never sell",
  "The passenger seat of a tow truck, watching your first car get hauled off",
  "A hospital waiting room at 2 a.m., vending machine humming, nobody talking",
  "Backstage after the biggest show of your life, and the only person you want to call doesn't pick up",
  "The DMV line the day after the deal cleared, still just another number in the room",
  "Watching your old block from a car with tinted windows, close enough to wave, too far to stop",
  "A jail visitation booth, phone cord too short, thirty minutes never enough",
  "The kitchen table where the eviction notice used to sit, now covered in contracts",
  "Standing at your own show's merch table before anyone knew your name",
  "The back pew at a funeral for someone you grew apart from before they passed",
  "A hotel room after the tour bus left without you",
  "The first time you send money home and it still doesn't feel like enough",
] as const;

export const RHYME_SCHEMES: readonly string[] = [
  "AABB, plain and punchy",
  "ABAB, alternating",
  "AAAA monorhyme, every bar landing the same",
  "Internal multis on beats 2 and 4",
  "Slant rhyme only, nothing perfect",
  "AABA with a dropped rhyme on the third bar",
  "Chain rhyme - last word of each bar starts the next",
  "Internal rhyme stacked three deep per bar",
  "Couplets that flip the rhyme scheme every quatrain",
] as const;

export const POCKETS: readonly string[] = [
  "Boom-bap, 88 BPM, sit behind the beat",
  "Trap, 140 BPM half-time, all in the hi-hats",
  "West Coast g-funk, 96 BPM, laid all the way back",
  "Double-time over a slow beat, 70 BPM",
  "No drums for the first four bars, then lock in",
  "Chopped and screwed pocket, every word dragged",
  "Boom-bap, 92 BPM, on top of the beat, aggressive",
  "Triplet flow, 130 BPM, tumbling",
  "Sparse pocket, more silence than syllables, 80 BPM",
] as const;

export const CONSTRAINTS: readonly string[] = [
  "No word longer than two syllables",
  "Every bar has to name a real place",
  "At least one bar with no rhyme at all",
  "Use a number in every other bar",
  "One bar has to be a direct quote from someone else",
  "No first person for the first four bars",
  "Every quatrain ends on the same word, different meaning",
  "At least two bars have to work without the beat",
  "One color repeats through the whole verse",
  "No adjectives - only nouns and verbs",
  "Every bar starts with a different letter, in order",
  "One bar has to be a lie you tell yourself",
  "Reference a smell at least once",
  "The last bar has to undercut the first",
] as const;

export const WORD_BANK: readonly string[] = [
  "concrete",
  "receipts",
  "static",
  "collateral",
  "porch light",
  "county line",
  "interest rate",
  "gospel",
  "curfew",
  "chrome",
  "layaway",
  "blood money",
  "dead bolt",
  "fine print",
  "static cling",
  "second mortgage",
  "bail bond",
  "streetlight",
  "open casket",
  "wire transfer",
] as const;
